### ISSUE TITLE
Improve testing to check the analyzer works

### ISSUE THREAD

**Issue by carlosms** [src-d/lookout-sonarcheck-analyzer#11]
Context in https://github.com/src-d/lookout-sonarcheck-analyzer/pull/10#discussion_r235656110

The tests were green even though the analyzer calls were failing because bblfsh was missing.

**Comment by smacker** [comment]
blocked by https://github.com/src-d/lookout-sdk/pull/32

**Comment by smacker** [comment]
now with new sdk tool it would fail in case of an error because of exit code 1.
but we still need to improve testing.
