### ISSUE TITLE
Add structural logging

### ISSUE THREAD

**Issue by bzz** [src-d/lookout-sonarcheck-analyzer#3]
Following [src-d conventions](https://github.com/src-d/guide/blob/master/engineering/conventions.md#logging) add a structural logging using `structlog`, here is an [example](http://stevetarver.github.io/2017/05/10/python-falcon-logging.html).

**Comment by smacker** [comment]
structlog isn't src-d default structured logger. ML team uses this one https://github.com/src-d/modelforge/blob/master/modelforge/slogging.py everywhere, which is not a standalone lib but a part of modelforge.

Taking into account that this analyzer is created for "testing and demo" standard python logger which is used right now should be fine.

In case we need to start produce log messages in json format for some reason we can just apply any existing library to change formatter of the standard logger. For example [python-json-logger](https://github.com/madzak/python-json-logger) (first link in google for me).

We may reconsider it when we have proper separate library for structed logging in python used across all src-d. Closing for now.
